import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distTaste = path.resolve(__dirname, '../dist/taste.js');
const distPortrait = path.resolve(__dirname, '../dist/taste-portrait.js');
const distTasteStore = path.resolve(__dirname, '../dist/taste-store.js');

let taste;
let portrait;
let tasteStoreMod;

try {
  taste = await import(distTaste);
  portrait = await import(distPortrait);
  tasteStoreMod = await import(distTasteStore);
} catch (err) {
  const msg = `dist taste portrait modules not found - run \`npm run build\` first. (${err.message})`;
  test('taste portrait modules available', (t) => { t.skip(msg); });
  process.exit(0);
}

async function withTasteHome(fn) {
  const previous = process.env.RAVEN_TASTE_HOME;
  const home = await mkdtemp(path.join(tmpdir(), 'raven-taste-portrait-home-'));
  process.env.RAVEN_TASTE_HOME = home;
  try {
    const store = new tasteStoreMod.FsTasteStore();
    await fn(home, store);
  } finally {
    if (previous === undefined) {
      delete process.env.RAVEN_TASTE_HOME;
    } else {
      process.env.RAVEN_TASTE_HOME = previous;
    }
  }
}

async function tempOutputDir() {
  return await mkdtemp(path.join(tmpdir(), 'raven-taste-portrait-out-'));
}

function rules() {
  return [
    {
      rule_id: 'MONO-COLOR',
      clause_text: 'Monochrome portfolio surfaces suppress hue unless a surface binding explicitly permits it.',
      category: 'color',
      severity_default: 'block',
      negative_prompt: 'No gradients, glow, or second accent hue.',
      owner: 'taste',
      delegate_to: '',
      scope: 'monochrome portfolio',
    },
    {
      rule_id: 'TYPE-JOBS',
      clause_text: 'Serif is for first-person quoted evidence only; sans carries structure; mono carries labels.',
      category: 'typography',
      severity_default: 'warn',
      negative_prompt: 'Do not use decorative serif headings.',
      owner: 'taste',
      delegate_to: '',
      scope: 'global',
    },
    {
      rule_id: 'PRODUCT-ATMOS',
      clause_text: 'Product surfaces may use saturated atmosphere when the binding opts into it.',
      category: 'color',
      severity_default: 'nit',
      negative_prompt: '',
      owner: 'taste',
      delegate_to: '',
      scope: 'product site',
    },
  ];
}

function assertHtmlSane(html) {
  assert.match(html, /^<!doctype html>/i);
  const styleOpen = (html.match(/<style>/g) || []).length;
  const styleClose = (html.match(/<\/style>/g) || []).length;
  assert.equal(styleOpen, styleClose);
  assert.ok(styleOpen >= 1);
  assert.match(html, /<\/html>\s*$/);
}

test('full profile renders all portrait sections from store data', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'portrait-full',
      rules: rules(),
      corpus: [
        {
          artifact: 'Quote with <script>alert("x")</script>',
          verdict: 'revise',
          violated_rule: 'MONO-COLOR',
          wrong: 'Rainbow glow and <script>alert("wrong")</script>',
          right: 'Near-black ink, graphite ramp, accent none',
        },
      ],
    });
    await taste.bindTasteSurface(store, 'portrait-full', {
      project: 'portfolio',
      surface: 'monochrome portfolio editorial',
      voice_note: 'Punchy editorial, no sales language.',
      design_notes: {
        color: 'Monochrome warm paper, accent none, zero hue.',
        typography: 'Fraunces only for quoted evidence; Inter carries structure.',
        motion: 'Curtain wipe and reveal only; reduced motion must render static.',
      },
    });
    await taste.recordTasteDecision(store, 'portrait-full', {
      project: 'portfolio',
      dimension: 'color',
      decision: 'Use ink, graphite, and paper only.',
      rejected: ['cyan glow', 'purple gradient'],
      why: 'The portfolio surface is monochrome.',
      source: 'user-corrected',
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'portrait-full', project: 'portfolio', output_dir: outDir });
    assert.equal(result.files.length, 1);
    assert.equal(result.index_path, undefined);
    assert.deepEqual(result.warnings, []);

    const html = await readFile(result.files[0].path, 'utf8');
    assertHtmlSane(html);
    assert.match(html, /Surface rules/);
    assert.match(html, /In-scope laws/);
    assert.match(html, /Wrong → right ledger/);
    assert.match(html, /Decision evidence/);
    assert.match(html, /Generated by Raven · portrait-full ·/);
    assert.ok(!html.includes('<script>alert("x")</script>'));
    assert.ok(html.includes('&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;'));
  });
});

test('sparse profile omits empty corpus and decision sections and warns', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, { name: 'portrait-sparse', rules: rules() });
    await taste.bindTasteSurface(store, 'portrait-sparse', {
      project: 'plain',
      surface: 'monochrome portfolio',
      design_notes: { color: 'Monochrome, accent none.' },
      voice_note: 'Quiet and direct.',
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'portrait-sparse', project: 'plain', output_dir: outDir });
    const html = await readFile(result.files[0].path, 'utf8');
    assertHtmlSane(html);
    assert.ok(!html.includes('corrections-section'));
    assert.ok(!html.includes('decisions-section'));
    assert.ok(result.warnings.some((warning) => /no corpus/.test(warning)));
    assert.ok(result.warnings.some((warning) => /no recorded decisions/.test(warning)));
  });
});

test('monochrome-scoped output contains no hue outside its palette tokens', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'portrait-mono',
      rules: rules(),
      corpus: [
        { artifact: 'color correction', verdict: 'revise', violated_rule: 'MONO-COLOR', wrong: 'red glow', right: 'graphite only' },
      ],
    });
    await taste.bindTasteSurface(store, 'portrait-mono', {
      project: 'mono',
      surface: 'monochrome portfolio',
      design_notes: { color: 'Monochrome only. Accent none. No hue.' },
      voice_note: 'Documentary, not decorative.',
    });
    await taste.recordTasteDecision(store, 'portrait-mono', { project: 'mono', dimension: 'color', decision: 'Suppress hue entirely.' });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'portrait-mono', project: 'mono', output_dir: outDir });
    const html = await readFile(result.files[0].path, 'utf8');
    const hexes = Array.from(new Set((html.match(/#[0-9a-fA-F]{6}\b/g) || []).map((hex) => hex.toLowerCase())));
    assert.deepEqual(hexes.sort(), ['#141412', '#4a4742', '#7d7870', '#f4f1ea', '#faf7f2'].sort());
  });
});

test('multi-binding render writes a gallery index linking every surface', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'portrait-gallery',
      rules: rules(),
      corpus: [
        { artifact: 'baseline', verdict: 'revise', violated_rule: 'TYPE-JOBS', wrong: 'serif heading', right: 'sans heading' },
      ],
    });
    await taste.bindTasteSurface(store, 'portrait-gallery', {
      project: 'portfolio',
      surface: 'monochrome portfolio editorial',
      design_notes: { color: 'Monochrome, accent none.' },
    });
    await taste.bindTasteSurface(store, 'portrait-gallery', {
      project: 'gym-product',
      surface: 'product site atmosphere',
      design_notes: { color: 'Deep navy with cyan, magenta, and mint atmosphere.', aesthetic: 'Glassmorphic product surface.' },
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'portrait-gallery', output_dir: outDir });
    assert.equal(result.files.length, 2);
    assert.ok(result.index_path);
    assert.ok(existsSync(result.index_path));

    const indexHtml = await readFile(result.index_path, 'utf8');
    assertHtmlSane(indexHtml);
    assert.match(indexHtml, /portfolio\.html/);
    assert.match(indexHtml, /gym-product\.html/);
    assert.match(indexHtml, /Bound taste surfaces/);

    for (const file of result.files) {
      assertHtmlSane(await readFile(file.path, 'utf8'));
    }
  });
});

test('audit_taste exempts data-taste-quote content from detectors and reports the exemption', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'quote-exempt',
      rules: [
        {
          rule_id: 'VOICE-RESTRAINT',
          clause_text: 'Register is editorial, never salesy.',
          category: 'voice',
          severity_default: 'warn',
          negative_prompt: 'Never use persuasion words (proven, supercharge).',
          owner: 'taste',
          delegate_to: '',
          scope: 'global',
        },
      ],
      corpus: [],
    });

    const quoted = '<html><body><blockquote data-taste-quote><p>we shipped a proven supercharge</p></blockquote><h1>Calm heading</h1></body></html>';
    const exempt = await taste.auditTaste(store, { profile: 'quote-exempt', html: quoted });
    assert.equal(exempt.findings.length, 0);
    assert.ok(exempt.quoted_evidence_exempt);
    assert.equal(exempt.quoted_evidence_exempt.elements, 1);
    assert.ok(exempt.quoted_evidence_exempt.chars > 0);

    const nested = '<html><body><div data-taste-quote><div><p>proven</p></div></div><p>plain copy after the quote</p></body></html>';
    const nestedResult = await taste.auditTaste(store, { profile: 'quote-exempt', html: nested });
    assert.equal(nestedResult.findings.length, 0);

    const bare = '<html><body><p>a proven supercharge of value</p></body></html>';
    const flagged = await taste.auditTaste(store, { profile: 'quote-exempt', html: bare });
    assert.ok(flagged.findings.length > 0);
    assert.equal(flagged.quoted_evidence_exempt, undefined);
  });
});

test('generated portrait passes audit_taste against its own surface (self-audit gate)', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'self-audit',
      rules: [
        {
          rule_id: 'VOICE-RESTRAINT',
          clause_text: 'Register is editorial, never salesy.',
          category: 'voice',
          severity_default: 'block',
          negative_prompt: 'Never use persuasion words (proven, shipped, supercharge, durable).',
          owner: 'taste',
          delegate_to: '',
          scope: 'global',
        },
        {
          rule_id: 'COLOR-NO-GRADIENT',
          clause_text: 'No purple/indigo/blue gradients, no glow.',
          category: 'color',
          severity_default: 'block',
          negative_prompt: 'Never use multi-hue gradients or glow.',
          owner: 'taste',
          delegate_to: '',
          scope: 'global',
        },
      ],
      corpus: [
        {
          artifact: 'hero copy with #0077C5 accents',
          verdict: 'revise',
          violated_rule: 'VOICE-RESTRAINT',
          wrong: 'we shipped a proven durable supercharge in rgba(179,136,255,0.12)',
          right: 'the tool renders each bound surface',
        },
      ],
    });
    await taste.bindTasteSurface(store, 'self-audit', {
      project: 'product',
      surface: 'product site',
      voice_note: 'Plain product register.',
      design_notes: { color: 'Warm off-white ground, one warm accent. No gradients, no glow.' },
    });
    await taste.recordTasteDecision(store, 'self-audit', {
      project: 'product',
      dimension: 'voice',
      decision: 'Copy states what the tool does; a proven-supercharge register was rejected.',
      rejected: ['salesy proven/shipped claim-headline copy'],
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'self-audit', project: 'product', output_dir: outDir });
    const html = await readFile(result.files[0].path, 'utf8');
    const audit = await taste.auditTaste(store, { profile: 'self-audit', project: 'product', html });
    assert.equal(audit.verdict, 'PASS', JSON.stringify(audit.findings, null, 2));
    assert.ok(audit.quoted_evidence_exempt && audit.quoted_evidence_exempt.elements > 0);
  });
});

test('family follows explicit color permissions, not adjacent vocabulary', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, { name: 'family-routing', rules: rules(), corpus: [] });
    await taste.bindTasteSurface(store, 'family-routing', {
      project: 'light-glass',
      surface: 'product site',
      design_notes: {
        color: 'Warm off-white paper ground. No gradients, no glow.',
        aesthetic: 'Flat-white blended with glassmorphic — translucent blurred layers for depth.',
      },
    });
    await taste.bindTasteSurface(store, 'family-routing', {
      project: 'saturated',
      surface: 'product site',
      design_notes: { color: 'Deep navy ground with saturated multi-hue color washes and discrete orbs.' },
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'family-routing', output_dir: outDir });
    const byProject = Object.fromEntries(result.files.map((file) => [file.project, file.path]));

    const lightGlass = await readFile(byProject['light-glass'], 'utf8');
    assert.match(lightGlass, /family-editorial-light/);
    assert.doesNotMatch(lightGlass, /radial-gradient/);

    const saturated = await readFile(byProject['saturated'], 'utf8');
    assert.match(saturated, /family-atmosphere/);
  });
});

test("document_kind:'portrait' skips note-fidelity honestly; 'artifact' still enforces it", async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'genre',
      rules: [
        {
          rule_id: 'VOICE-RESTRAINT',
          clause_text: 'Register is editorial, never salesy.',
          category: 'voice',
          severity_default: 'block',
          negative_prompt: 'Never use persuasion words (proven, supercharge).',
          owner: 'taste',
          delegate_to: '',
          scope: 'global',
        },
      ],
      corpus: [],
    });
    await taste.bindTasteSurface(store, 'genre', {
      project: 'webgl-product',
      surface: 'product site',
      design_notes: {
        color: 'Warm off-white ground, one accent. No gradients, no glow.',
        libraries: 'three.js hero scene with a WebGL canvas.',
      },
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'genre', project: 'webgl-product', output_dir: outDir });
    const html = await readFile(result.files[0].path, 'utf8');

    // As an artifact OF the surface, the missing three.js canvas is a block.
    const asArtifact = await taste.auditTaste(store, { profile: 'genre', project: 'webgl-product', html });
    assert.equal(asArtifact.verdict, 'BLOCK');
    assert.ok((asArtifact.fidelity_findings || []).some((f) => f.rule_id === 'NOTE-libraries'));
    assert.equal(asArtifact.note_fidelity_skipped, undefined);

    // As a document ABOUT the surface, notes are not acceptance criteria —
    // and the skip is announced, never silent.
    const asPortrait = await taste.auditTaste(store, { profile: 'genre', project: 'webgl-product', html, document_kind: 'portrait' });
    assert.equal(asPortrait.verdict, 'PASS', JSON.stringify(asPortrait.findings, null, 2));
    assert.equal(asPortrait.fidelity_findings, undefined);
    assert.equal(asPortrait.note_assessments, undefined);
    assert.equal(asPortrait.build_hints, undefined);
    assert.ok(typeof asPortrait.note_fidelity_skipped === 'string' && asPortrait.note_fidelity_skipped.includes('portrait'));
  });
});

test('anime.js is a named-library escalation: absent motion blocks as an artifact, is skipped as a portrait', async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, { name: 'anime-lib', rules: rules(), corpus: [] });
    await taste.bindTasteSurface(store, 'anime-lib', {
      project: 'motion-site',
      surface: 'product site',
      design_notes: {
        color: 'Warm off-white ground, one accent. No gradients, no glow.',
        libraries: 'anime.js staggered entrance choreography and SVG timelines.',
      },
    });

    // A live capture whose animation surface is empty — the anime.js note is unmet.
    const stillTraits = {
      source: 'live', scheme: 'light', bg_luminance: 0.98, text_density: 0.4,
      section_count: 5, image_count: 3, video_count: 0, canvas_count: 0,
      webgl: false, backdrop_filter: false, animation_count: 0, scroll_effects: false,
      font_families: ['Inter'], max_heading_px: 48, gradient_count: 0,
      loader_hint: false, viewport_fill: 0.6,
    };
    const html = '<main><h1>Motion Site</h1><p>Nothing animates here.</p></main>';

    // As an artifact OF the surface, a wholly-absent NAMED library (anime.js) blocks
    // — the same escalation three.js/gsap/lottie get, not a soft warn.
    const asArtifact = await taste.auditTaste(store, { profile: 'anime-lib', project: 'motion-site', html, traits: stillTraits });
    assert.equal(asArtifact.verdict, 'BLOCK', JSON.stringify(asArtifact.fidelity_findings, null, 2));
    const lib = (asArtifact.fidelity_findings || []).find((f) => f.rule_id === 'NOTE-libraries');
    assert.ok(lib, 'anime.js absence must surface as NOTE-libraries');
    assert.equal(lib.severity, 'block', 'a named library escalates to block, not warn');

    // As a document ABOUT the surface, the anime.js note is not an acceptance criterion.
    const asPortrait = await taste.auditTaste(store, { profile: 'anime-lib', project: 'motion-site', html, traits: stillTraits, document_kind: 'portrait' });
    assert.equal(asPortrait.fidelity_findings, undefined);
    assert.ok(typeof asPortrait.note_fidelity_skipped === 'string');
  });
});

test("document_kind:'portrait' still BLOCKS a real profile-rule violation (guarantee #1)", async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, {
      name: 'portrait-rules',
      rules: [
        {
          rule_id: 'COLOR-NO-GRADIENT',
          clause_text: 'No gradients.',
          category: 'color',
          severity_default: 'block',
          negative_prompt: 'Never use multi-hue gradients.',
          owner: 'taste',
          delegate_to: '',
          scope: 'global',
        },
      ],
      corpus: [],
    });
    await taste.bindTasteSurface(store, 'portrait-rules', {
      project: 'p',
      surface: 'product site',
      // A named library the portrait can't literally be — proves note-fidelity
      // is skipped while the real color rule below still binds.
      design_notes: { libraries: 'three.js WebGL hero scene.' },
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'portrait-rules', project: 'p', output_dir: outDir });
    let html = await readFile(result.files[0].path, 'utf8');
    // Inject a REAL, un-quoted gradient into the portrait body — a genuine
    // taste-rule violation that must survive portrait mode.
    html = html.replace('</main>', '<div style="background:linear-gradient(90deg,#ff0000,#0000ff)">x</div></main>');

    const audit = await taste.auditTaste(store, { profile: 'portrait-rules', project: 'p', html, document_kind: 'portrait' });
    // Note-fidelity is skipped (the missing three.js scene is NOT a finding)...
    assert.ok(typeof audit.note_fidelity_skipped === 'string', 'note-fidelity should be skipped');
    assert.equal(audit.fidelity_findings, undefined);
    // ...but the real gradient MUST still block. Portrait mode only silences
    // note-fidelity, never the profile's own taste rules.
    assert.equal(audit.verdict, 'BLOCK', JSON.stringify(audit.findings, null, 2));
    assert.ok(audit.findings.some((f) => f.rule_id === 'COLOR-NO-GRADIENT'), 'gradient rule must still fire in portrait mode');
  });
});

test("wantsLightGlass rejects negated glass phrasing (no false glass)", async () => {
  await withTasteHome(async (_home, store) => {
    await taste.createTasteProfile(store, { name: 'neg-glass', rules: rules(), corpus: [] });
    await taste.bindTasteSurface(store, 'neg-glass', {
      project: 'anti-glass',
      surface: 'product site',
      // Explicitly forbids glass — the generator must NOT apply glass CSS.
      design_notes: {
        color: 'Warm off-white ground, one accent. No gradients, no glow.',
        aesthetic: 'Flat matte surfaces. No frosted glass, avoid glass panels.',
      },
    });
    await taste.bindTasteSurface(store, 'neg-glass', {
      project: 'yes-glass',
      surface: 'product site',
      design_notes: {
        color: 'Warm off-white ground, one accent. No gradients, no glow.',
        aesthetic: 'Frosted-glass panels over a light bone ground.',
      },
    });

    const outDir = await tempOutputDir();
    const result = await portrait.generateTastePortrait({ store, profile: 'neg-glass', output_dir: outDir });
    const byProject = Object.fromEntries(result.files.map((file) => [file.project, file.path]));

    const anti = await readFile(byProject['anti-glass'], 'utf8');
    assert.doesNotMatch(anti, /class="[^"]*glass-light/, 'negated glass note must not apply glass CSS');
    assert.doesNotMatch(anti, /backdrop-filter/);

    const yes = await readFile(byProject['yes-glass'], 'utf8');
    assert.match(yes, /class="[^"]*glass-light/, 'un-negated glass note must apply glass CSS');
    assert.match(yes, /backdrop-filter/);
  });
});
