import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
const dir = import.meta.dirname;
const file = pathToFileURL(path.join(dir, 'index.html')).href;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 860 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto(file);
await p.locator('#save-button').click();
await p.waitForFunction(() => document.getElementById('record-state').textContent === 'visible');
await p.screenshot({ path: path.join(dir, 'state-visible.png') });
await p.locator('.snackbar').hover();
await p.waitForTimeout(300);
await p.locator('.snackbar').screenshot({ path: path.join(dir, 'snackbar-hover.png') });
await p.locator('.snackbar__undo').focus();
await p.waitForTimeout(200);
await p.locator('.snackbar').screenshot({ path: path.join(dir, 'snackbar-focus.png') });
await b.close();
